package com.example.helperapp.utils;

public enum GenieStatusCodes {
    SERVICE_COMPLETED,
    SERVICE_PENDING,
    SERVICE_CANCELLED,
    SERVICE_REJECTED,
    SERVICE_PAYMENT_PENDING,
    SERVICE_PAYMENT_COMPLETED,
    SERVICE_PAYMENT_REJECTED,
    REFUND_INITIATED,
    REFUND_COMPLETED,
    TICKET_RAISED,
    TICKET_CLOSED
}
